version: '3'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - 5775:5775/udp # accept zipkin.thrift over compact thrift protocol
      - 6831:6831/udp # accept jaeger.thrift over compact thrift protocol
      - 6832:6832/udp # accept jaeger.thrift over binary thrift protocol
      - 5778:5778 # serve configs
      - 16686:16686 # serve frontend
      - 14268:14268 # accept jaeger.thrift directly from clients
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"